### PR TITLE
Migrate Fabric8 Maven Plugin to Eclipse JKube

### PR DESCRIPTION
**Pull request by rohanKanojia**
[Fabric8 Maven Plugin](https://github.com/fabric8io/fabric8-maven-plugin) is going to be marked deprecated soon and
[Eclipse JKube](https://github.com/eclipse/jkube) would be supported in future.

This PR changes FMP maven coordinates to Eclipse JKube

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@ianwatsonrh @eschabell : Could you please review this whenever you get time?

**Comment by rohanKanojia** [comment]
polite ping, any update regarding this? Shall I close this PR if this repository is not active?

**Comment by ehelms** [comment]
Given this lab was in 2018, I do not expect this repository to receive any further updates or maintenance.

**Comment by rohanKanojia** [comment]
If possible, please mark this repository as read only so that people don't get motivated to send PRs

**Pull request closed without merging**
